name: Integration test on PR

on:
  push:
    branches:
    - 'ci/**'
  pull_request:
    branches:
    - main
  workflow_call: # Unit test runs only on workflow_call event

jobs:
  build:
    name: "Run integration tests"

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        cache: 'maven'
    
    - name: Testing
      run: ./mvnw clean integration-test 